matrix:
  include:
    - language: node_js
      node_js:
        - "12"
      before_install:
        - cd node/
      install: 
        - npm install
      script:
        - npm test

notifications:
  email:
    on_success: never
    on_failure: always
